version: 3

build_arg_defaults: 
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies: 
  galaxy: requirements.yml
  system:
    - krb5-workstation
    - krb5-libs
    - gcc
    - python3.11-devel
    - krb5-devel
    - openssl-devel
    - libffi-devel
  python:
    - pywinrm
    - pywinrm[kerberos]
    - pyspnego[kerberos]
options:
  package_manager_path: /usr/bin/microdnf

images: 
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest
# Custom package manager path for the RHEL based images

additional_build_files:
  - src: files/krb5.conf
    dest: configs

additional_build_steps: 
  prepend_base:
    - RUN echo This is a prepend base command!
    - COPY _build/configs/krb5.conf /etc/krb5.conf
  
  prepend_galaxy:
    # Environment variables used for Galaxy client configurations
    - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://console.redhat.com/api/automation-hub/content/published/
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    # define a custom build arg env passthru - we still also have to pass
    # `--build-arg ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN` to get it to pick it up from the env
    - ARG ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN

  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc


  